# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers
trigger:
  batch: true
  branches:
    include:
      - '*'

# echo 'strategy:'; echo '  matrix:'; for dir in $(git ls-files '*/Dockerfile' | xargs -n1 dirname | sort -u); do tag="${dir//'/'/-}"; echo "    $tag:"; echo "      azureImage: 'ubuntu-latest'"; echo "      buildContext: '$dir'"; done
strategy:
  matrix:
    apt-cacher-ng:
      azureImage: 'ubuntu-latest'
      buildContext: 'apt-cacher-ng'
    backblaze-b2:
      azureImage: 'ubuntu-latest'
      buildContext: 'backblaze-b2'
    beets:
      azureImage: 'ubuntu-latest'
      buildContext: 'beets'
    byzanz:
      azureImage: 'ubuntu-latest'
      buildContext: 'byzanz'
    caff:
      azureImage: 'ubuntu-latest'
      buildContext: 'caff'
    certbot:
      azureImage: 'ubuntu-latest'
      buildContext: 'certbot'
    debian-devel:
      azureImage: 'ubuntu-latest'
      buildContext: 'debian/devel'
    debian-experimental:
      azureImage: 'ubuntu-latest'
      buildContext: 'debian/experimental'
    debian-frankendebian:
      azureImage: 'ubuntu-latest'
      buildContext: 'debian/frankendebian'
    debian-rc-buggy:
      azureImage: 'ubuntu-latest'
      buildContext: 'debian/rc-buggy'
    debian-ubuntu-devel:
      azureImage: 'ubuntu-latest'
      buildContext: 'debian/ubuntu-devel'
    dell-netextender:
      azureImage: 'ubuntu-latest'
      buildContext: 'dell-netextender'
    dell-netextender-gui:
      azureImage: 'ubuntu-latest'
      buildContext: 'dell-netextender/gui'
    diffoscope:
      azureImage: 'ubuntu-latest'
      buildContext: 'diffoscope'
    docker-master:
      azureImage: 'ubuntu-latest'
      buildContext: 'docker-master'
    docker-master-dind:
      azureImage: 'ubuntu-latest'
      buildContext: 'docker-master/dind'
    docker-master-git:
      azureImage: 'ubuntu-latest'
      buildContext: 'docker-master/git'
    docker-tianon:
      azureImage: 'ubuntu-latest'
      buildContext: 'docker-tianon'
    duplicity:
      azureImage: 'ubuntu-latest'
      buildContext: 'duplicity'
    ehour:
      azureImage: 'ubuntu-latest'
      buildContext: 'ehour'
    exim4:
      azureImage: 'ubuntu-latest'
      buildContext: 'exim4'
    github-hub:
      azureImage: 'ubuntu-latest'
      buildContext: 'github-hub'
    github-pages:
      azureImage: 'ubuntu-latest'
      buildContext: 'github-pages'
    glxgears:
      azureImage: 'ubuntu-latest'
      buildContext: 'glxgears'
    gmpydl:
      azureImage: 'ubuntu-latest'
      buildContext: 'gmpydl'
    gmvault:
      azureImage: 'ubuntu-latest'
      buildContext: 'gmvault'
    google-cloud-print-connector:
      azureImage: 'ubuntu-latest'
      buildContext: 'google-cloud-print-connector'
    google-musicmanager:
      azureImage: 'ubuntu-latest'
      buildContext: 'google-musicmanager'
    grafana:
      azureImage: 'ubuntu-latest'
      buildContext: 'grafana'
    haproxy-sks:
      azureImage: 'ubuntu-latest'
      buildContext: 'haproxy-sks'
    jenkins:
      azureImage: 'ubuntu-latest'
      buildContext: 'jenkins'
    jenkins-slave:
      azureImage: 'ubuntu-latest'
      buildContext: 'jenkins/slave'
    jenkins-slave-debian:
      azureImage: 'ubuntu-latest'
      buildContext: 'jenkins/slave/debian'
    kafka:
      azureImage: 'ubuntu-latest'
      buildContext: 'kafka'
    kgb-bot:
      azureImage: 'ubuntu-latest'
      buildContext: 'kgb-bot'
    latex:
      azureImage: 'ubuntu-latest'
      buildContext: 'latex'
    makemkv:
      azureImage: 'ubuntu-latest'
      buildContext: 'makemkv'
    mojo:
      azureImage: 'ubuntu-latest'
      buildContext: 'mojo'
    mutt-gmail:
      azureImage: 'ubuntu-latest'
      buildContext: 'mutt-gmail'
    network-toolbox-alpine:
      azureImage: 'ubuntu-latest'
      buildContext: 'network-toolbox/alpine'
    network-toolbox-debian:
      azureImage: 'ubuntu-latest'
      buildContext: 'network-toolbox/debian'
    perl:
      azureImage: 'ubuntu-latest'
      buildContext: 'perl'
    phpmyadmin:
      azureImage: 'ubuntu-latest'
      buildContext: 'phpmyadmin'
    plex-media-server:
      azureImage: 'ubuntu-latest'
      buildContext: 'plex/media-server'
    prometheus:
      azureImage: 'ubuntu-latest'
      buildContext: 'prometheus'
    prometheus-blackbox-exporter:
      azureImage: 'ubuntu-latest'
      buildContext: 'prometheus/blackbox-exporter'
    prometheus-node-exporter:
      azureImage: 'ubuntu-latest'
      buildContext: 'prometheus/node-exporter'
    rtorrent:
      azureImage: 'ubuntu-latest'
      buildContext: 'rtorrent'
    ruby-passenger:
      azureImage: 'ubuntu-latest'
      buildContext: 'ruby-passenger'
    ruby-unicorn:
      azureImage: 'ubuntu-latest'
      buildContext: 'ruby-unicorn'
    ruby-unicorn-nginx:
      azureImage: 'ubuntu-latest'
      buildContext: 'ruby-unicorn-nginx'
    sbuild:
      azureImage: 'ubuntu-latest'
      buildContext: 'sbuild'
    skype:
      azureImage: 'ubuntu-latest'
      buildContext: 'skype'
    slack:
      azureImage: 'ubuntu-latest'
      buildContext: 'slack'
    sleeping-beauty:
      azureImage: 'ubuntu-latest'
      buildContext: 'sleeping-beauty'
    speedtest:
      azureImage: 'ubuntu-latest'
      buildContext: 'speedtest'
    steam:
      azureImage: 'ubuntu-latest'
      buildContext: 'steam'
    travis-cli:
      azureImage: 'ubuntu-latest'
      buildContext: 'travis-cli'
    true:
      azureImage: 'ubuntu-latest'
      buildContext: 'true'
    wine-32:
      azureImage: 'ubuntu-latest'
      buildContext: 'wine/32'
    wine-64:
      azureImage: 'ubuntu-latest'
      buildContext: 'wine/64'
    xen-orchestra:
      azureImage: 'ubuntu-latest'
      buildContext: 'xen-orchestra'
    ymlfmt:
      azureImage: 'ubuntu-latest'
      buildContext: 'ymlfmt'

pool:
  vmImage: $(azureImage)

steps:
- bash: |
    set -Eeuo pipefail -x
    #git clone --depth 1 https://github.com/docker-library/official-images.git ~/oi
    git clone --depth 1 https://github.com/tianon/stackbrew.git -b azure ~/oi
    ~/oi/.azure/wait-for-docker.sh
    ~/oi/.azure/set-docker-tag.sh
  displayName: 'Prepare environment'

- bash: |
    set -Eeuo pipefail -x
    source <(wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh')
  displayName: 'Apply pgp-happy-eyeballs'
  condition: eq( variables['Agent.OS'], 'Linux' )

- bash: |
    set -Eeuo pipefail -x
    docker build -t '$(dockerTag)' .
  workingDirectory: $(buildContext)
  displayName: '"docker build"'

- bash: |
    set -Eeuo pipefail -x
    ~/oi/test/run.sh '$(dockerTag)'
  displayName: 'Run tests'
  condition: eq( variables['Agent.OS'], 'Linux' )
  enabled: false # TODO enable this!

# vim:set tabstop=2 shiftwidth=2:
